### ISSUE TITLE
Using Slim Framework for the GUI

### ISSUE THREAD

**Issue by salmankaleem5** [salmankaleem5/hireahusky#1]
I think we should use Slim framework for the front end, I already implemented it but I thought I should ask what you guys thought. It helps with routing (sending users to different pages) which will definitely help when dealing with logged-in/logged-out users. And because we're making an API it has methods to make requesting data easy. 

I didn't want to make big project decisions on my own. What do you guys think?

**Comment by ghost** [comment]
I think it's a good idea :)

On Apr 9, 2015, at 9:58 PM, Salman notifications@github.com wrote:

I think we should use Slim framework for the front end, I already
implemented it but I thought I should ask what you guys thought. It helps
with routing (sending users to different pages) which will definitely help
when dealing with logged-in/logged-out users. And because we're making an
API it has methods to make requesting data easy.

I didn't want to make big project decisions on my own. What do you guys
think?

—
Reply to this email directly or view it on GitHub
https://github.com/salmankaleem5/hireahusky/issues/1.
